name: 🐛 Bug Report
description: Report a reproducible issue or unexpected behavior
title: "[Bug]: "
labels: [bug]

body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug. Please fill out the following details to help us reproduce and fix the issue.

  - type: input
    id: environment
    attributes:
      label: Environment
      description: Describe the environment where the bug occurred (e.g., OS, browser, Go version, etc.)
      placeholder: "e.g. macOS 13.5, Go 1.22.0"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce the issue?
      placeholder: |
        1. Clone the repository
        2. Run the application with expected input
        3. Observe the issue
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happened instead.
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / Error Output
      description: Paste any relevant logs, error messages, or screenshots.
      placeholder: |
        ```
        error: unexpected behavior
        ```
      render: shell

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to avoid duplicates.
        - label: I have provided sufficient steps to reproduce the issue.
