name: 📚 Documentation Update
description: Suggest improvements or corrections for the documentation
title: "[Docs]: "
labels: [documentation]

body:
  - type: markdown
    attributes:
      value: |
        Thank you for helping improve the documentation!  
        Please provide as much detail as possible so we can address your suggestion effectively.

  - type: input
    id: location
    attributes:
      label: Documentation Location
      description: Where in the documentation did you notice the issue?
      placeholder: e.g., README.md, CONTRIBUTING.md, docs/usage.md
    validations:
      required: true

  - type: textarea
    id: issue
    attributes:
      label: Description of the Issue
      description: What’s wrong, missing, or unclear?
      placeholder: |
        The example command in the README uses a deprecated flag.

    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Improvement
      description: How would you improve the documentation?
      placeholder: |
        Update the example to use the new flag: `--template=default`

  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Any other relevant details or links
      placeholder: Add any context, related issues, or screenshots here.

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to avoid duplicates.
        - label: I have described the issue and suggestion clearly.
